apiVersion: v1
kind: Service
metadata:
    name: mongo
    labels:
        app: mongo
spec:
    type: NodePort
    selector:
        app: mongo
    ports:
        - protocol: TCP
          nodePort: 30002
          port: 27017