apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodejs-deploy
spec:
    selector:
        matchLabels:
            app: nodejs-deploy
    template:
        metadata:
            labels:
                app: nodejs-deploy
        spec:
            containers:
                - name: nodejs-deploy
                  image: alejandro1050/back-nodejs:1.0
                  ports:
                  - containerPort: 8000
                  env:
                    - name: MONGO_DB
                      valueFrom:
                          configMapKeyRef:
                              name: db-config
                              key: db_name
                    - name: MONGO_HOST
                      value: mongo
                    - name: MONGO_PORT
                      valueFrom:
                          configMapKeyRef:
                              name: db-config
                              key: db_port